version: "3.8"

services:
  nodeserver:
    container_name: nodeserver
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - nginx
    networks:
      - nodeserver-nginx
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nodeserver-nginx
  
networks:
  nodeserver-nginx: